### ISSUE TITLE
Any way to compile this on a macintosh?

### ISSUE THREAD

**Issue by kenpchess** [PogSmok/pgn-reader#1]
Hello! Looks very nice and simple! I tried to compile this on a mac and got several compile errors (too many to list). Do you have any way to test compile this on a mac? Thanks in advance for any help!  -kenpchess

**Comment by PogSmok** [comment]
The Alpha version was not meant to be used on any OS except Linux. Version Beta and beyond will all be compatible with Windows and Linux. I have no intention of testing for MacOS, but it should also be compatible.

**Comment by kenpchess** [comment]
Thanks so much for the info. I tried version beta and it compiled and ran fine on my mac! Even though I mostly use GUI's for my chess hobby, I have always wanted a "terminal" pgn viewer as I have an extra 16 inch monitor that I use as a programmers console, etc. to view code and various other tasks.

This works quite well (I will probably modify the chessboard view somewhat, dashes instead of zero for empty square, etc.). Thanks again and I will watch your progress on this project.

- kenpchess
>
